In [1]:
import numpy as np
import pprint
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from environment import GridWorldEnv

In [2]:
pp = pprint.PrettyPrinter(indent=2)
env = GridWorldEnv()

In [3]:
def value_iteration(env, theta=0.0001, discount_factor=0.99, max_iterations=1000):
    """
    Value Iteration Algorithm.
    
    Args:
        env: Custom GridWorldEnv environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
        max_iterations: Maximum number of iterations to perform.
        
    Returns:
        A tuple (policy, V) of the optimal policy and the optimal value function.
    """
    
    def one_step_lookahead(state, V):
        """
        Helper function to calculate the value for all actions in a given state.
        
        Args:
            state: The state to consider (runner's position as a tuple)
            V: The value to use as an estimator, numpy array of shape (n, n)
        
        Returns:
            A vector of length env.action_space containing the expected value of each action.
        """
        A = np.zeros(env.action_space)
        for a in range(env.action_space):
            env.reset()
            env.runner_pos = np.array(state)
            next_state, reward, done = env.step(a)
            next_runner_pos = tuple(next_state[:2])
            if done:
                A[a] = reward
            else:
                A[a] = reward + discount_factor * V[next_runner_pos]
        return A
    
    V = np.zeros((env.n, env.n))
    policy = np.zeros((env.n, env.n), dtype=int)

    for iteration in range(max_iterations):
        delta = 0
        for i in range(env.n):
            for j in range(env.n):
                old_v = V[i, j]
                A = one_step_lookahead((i, j), V)
                best_action_value = np.max(A)
                best_action = np.argmax(A)
                
                V[i, j] = best_action_value
                policy[i, j] = best_action
                delta = max(delta, abs(old_v - V[i, j]))
        
        if delta < theta:
            print(f"Value iteration converged after {iteration+1} iterations.")
            break
    else:
        print(f"Value iteration did not converge after {max_iterations} iterations.")
    
    return policy, V

In [4]:
policy, v = value_iteration(env)

print("\nPolicy (0=N, 1=NE, 2=E, 3=SE, 4=S, 5=SW, 6=W, 7=NW):")
print(policy)

print("\nValue Function:")
print(v)

Value iteration converged after 265 iterations.

Policy (0=N, 1=NE, 2=E, 3=SE, 4=S, 5=SW, 6=W, 7=NW):
[[3 3 3 3 3 3 3 3 3 3 3 3 3 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 3 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 3 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 3 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 6 6]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 5 5]]

Value Function:
[[99.99756555 99.9975899  99.9975899  99.997614   99.997614   99.99763786
  99.99763786 99.99766148 99.99766148 99.99768486 99.99768486 99.99770801
  99.99770801 99.99773093 99.99773093]
 [99.997614   99.99763786 99.99763786 99.99766148 99.99766148 99.99768486
  99.99768486 99.99770801 99.99770801 99.99773093 99.99773093 99.99775363
  99.99775363 99.99777609 99.99777609]
 [99.997614